apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pushover-credentials
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: local-vault-store
    kind: SecretStore
  target:
    name: pushover-credentials
    creationPolicy: Owner
  data:
    - secretKey: USER_KEY
      remoteRef:
        key: pushover
        property: user_key
    - secretKey: APP_TOKEN
      remoteRef:
        key: pushover
        property: api_token
