apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-service-discovery
rules:
  # Permissions required for the EndpointSlice Informer
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
  # Permissions required to read Service metadata/annotations
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-service-discovery-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-service-discovery
  apiGroup: rbac.authorization.k8s.io