# Replica count for the prober
replicaCount: 1

# Image configuration for the prober
image:
  repository: ghcr.io/demirdilek/kube-prober
  pullPolicy: IfNotPresent
  tag: "dev"

# Service configuration for the prober
service:
  type: ClusterIP
  port: 8080

# Resource requests and limits for the prober container
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

# Eigene Werte für dein kube-prober Chart:
dashboards:
  enabled: true
  label: grafana_dashboard
  labelValue: "1"

# Grafana-Startseite festlegen (über das Grafana-Subchart):
grafana:
  grafana.ini:
    dashboards:
      default_home_dashboard_path: /tmp/dashboards/kube_prober_dashboard.json

# values.yaml (Default / Dev)
httpbin:
  enabled: true