name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.5'
          cache: true

      - name: Run Tests
        run: go test -v -race ./...

      - name: Build stripped binary
        run: CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o api-prober .