name: Linting (Scripts & Helm)

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'scripts/**'
      - 'helm/**'
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - 'scripts/**'
      - 'helm/**'

jobs:
  lint-scripts:
    name: ShellCheck (Scripts)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './scripts'

  lint-helm:
    name: Helm Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Helm
        uses: azure/setup-helm@v5.0.1
        with:
          version: 'v3.14.0'

      - name: Run Helm Lint
        run: |
          helm lint helm/kube-prober